FACA x SER 5.
FACA y SER 3.
MOSTRE SOME x COM y.
FACA a SER 4.
FACA b SER 2.
MOSTRE MULTIPLIQUE a POR b.
MOSTRE SOME 10 COM 20.
MOSTRE MULTIPLIQUE 5 POR 3.
MOSTRE SOME x COM 10.
MOSTRE MULTIPLIQUE a POR 3.